ALTER TABLE pedido
    ADD COLUMN forma_pagamento VARCHAR(20) NOT NULL DEFAULT 'DINHEIRO',
    ADD COLUMN pago BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE pedido
    ALTER COLUMN forma_pagamento DROP DEFAULT;
